## Spatial Metapopulation Model {#sec-MPMspec}

## Motivation

## Formulation

@jacquez1988

We employ a basic $SIR$ compartmental model, assuming no births and deaths, with a total of $N$ individuals. $$ S + I  + R = N$$ {#eq-ConstantTotalPopulation}

We divide the population into $n$ connected sub-populations,hereafter 'patches', with $N_i$ denoting the population of patch $i$ (note that $N = \sum\limits_{i=1}^{n}N_i$).

Let $S_i$, $I_i$, $R_i$ respectively denote the number of susceptible, infected and recovered individuals in Patch $i$ (noting also that $N_i = S_i + I_i + R_i$). Also, since $R_i = N_i - S_i - I_i$, we will not explicitly show $R_i$ in the equations hereafter (thought this could be calculated at any time)

Individuals coming into contact with an infective, whether within or without patch, become infected at a rate $\beta$.

While individuals do not migrate between patches, infectives from patch $i$ infect - individuals from $j$ with a proportion $\phi_{ij}$.

The force of infection in patch $i$ given by $$
\Lambda_i = \beta \sum\limits_{j}^{n}\phi_{ij}I_j
$$

And thus the force of infection vector $$\Lambda = \beta I \Phi$$ {#eq-FOIv}

Where $I$ is the vector of patch infection counts, and $\Phi$ is the mixing matrix.

### Construction of mixing matrix

Instead of constructing the mixing matrix from empirical OD data, we specified the matrix analytically to encode the hierarchical structure of the SA classification.

The main constraint employed was that patches within the same level $L$ SA region would mix together more strongly than those not. Nevertheless, because of a higher level enclosing group (in the case of Melbourne, the state level grouping), we only need to specify a series of coefficients which correspond to the lowest level grouping in which two patches co-occur. Furthermore, to ensure the matrix rows sum to one, mixing is also proportional to the fraction of the population of the grouping region comprised by the patch.

for any two patches $i$ and $j$,

$i, j$ are patches

$S_{i}^{L}$ is the set of patches in level $L$ $N_i$ is the population of $i$ $N_{i}^{L}$ is the population of $S_{i}^{L}$ $\xi^{L}(\delta)$ is the proportion of mixing that occurs within $S_{i}^{L}$ but not$S_{i}^{L-1}$

The intra level mixing coefficients $\xi_L$ comprise the vector $\xi$. Constraining the elements of $\xi$ s.t. $\sum\limits_{L = 1}^{L} \xi_i = 1$ (where $L$ is the highest level grouping) ensures the rows of the mixing matrix sum to unity.\

-More verbosity

-Be more explicit about SA Levels

-Mention Mixing with PPMM

## Implementation


```pseudocode
#| label: alg-quicksort
#| html-indent-size: "1.2em"
#| html-comment-delimiter: "//"
#| html-line-number: true
#| html-line-number-punc: ":"
#| html-no-end: false
#| pdf-placement: "htb!"
#| pdf-line-number: true

\begin{algorithm}
\caption{Quicksort}
\begin{algorithmic}
\Procedure{Quicksort}{$A, p, r$}
  \If{$p < r$}
    \State $q = $ \Call{Partition}{$A, p, r$}
    \State \Call{Quicksort}{$A, p, q - 1$}
    \State \Call{Quicksort}{$A, q + 1, r$}
  \EndIf
\EndProcedure
\Procedure{Partition}{$A, p, r$}
  \State $x = A[r]$
  \State $i = p - 1$
  \For{$j = p$ to $r - 1$}
    \If{$A[j] < x$}
      \State $i = i + 1$
      \State exchange
      $A[i]$ with     $A[j]$
    \EndIf
    \State exchange $A[i]$ with $A[r]$
  \EndFor
\EndProcedure
\end{algorithmic}
\end{algorithm}
```

The model was implemented as continuous time markov chain, with discrete state variables $$S_{i}(t), I_{i}(t) \in {0,1,2,...N_{i}}$$ where $t\in [0, \infty)$

at $t = 0$, a randomly selected patch, $i$, is seeded with $I = 10$ invectives, such that $$S_{i}(0) = N_{i} - 10, I_{i}(0) = 10$$ and the remaining patches are disease free $$S_j(0) = N_j, I_j(0) =0, i\neq j $$

at $t>0$ possible changes in state ('events') are infection at a patch $i$ (if $S_i \geq 1$ & $I \geq 1$), or recovery at patch $i$ (if $I_i \geq 1$). Rates for these events are given in @tbl-EventRates

| Event                  | State change         | Rate            |
|------------------------|----------------------|-----------------|
| Infection in patch $i$ | $\{S_i -1, I_i +1\}$ | $S_i \Lambda_i$ |
| Recovery in patch $i$  | $\{I_i - 1\}$        | $\gamma I_i$    |

: Event Rates {#tbl-EventRates}

Due to the Markov property, events occur after a exponentially distributed time with parameter equal to the sum of all event rates $$\Delta t \sim Exp(\lambda)$$ where

$\lambda = \sum\limits_{i}^{n}S_i \Lambda_i + \gamma I_i$

at $t + \delta t$, a random event from @tbl-EventRates will occur with probability directly proportional to it's rate.

When the system enters a disease free equilibrium state (i.e. $I = 0$), the implementation is complete.

## Example: Greater Melbourne Area Spatial Metapopulation model {#sec-MossGmelb}
