---
title: "Chapter 4. Modelling interventions different scales"
editor: visual
---


```{r}
library(tidyverse)
```

```{r}
sim_dirs <- list.files("../../data/sims/new", recursive = TRUE)

tot_dirs <- sim_dirs[!str_detect(sim_dirs, "patchinf|patchsus|summary")] %>% 
  paste0("../../data/sims/new/", .)

sims <- read_csv(tot_dirs, col_names = c("t", "S", "I"), skip = 1, id = "sim" )

sims <-  sims |>
  filter(t != "Int64", grepl("HPMM", sim)) %>% 
  mutate(
    S = as.numeric(S),
    I = as.numeric(I),
    t = as.numeric(t),
    SA = str_extract(sim, "SA./SA(.)", 1),
    Mixmat = str_extract(sim, "SA./SA._..._..._(HPMM|HMM|OD)_", 1),
    mu = str_extract(sim, "SA./SA._..._..._.{3,4}_(.{0,3})_", 1),
    Intervention = factor(str_extract(sim,"SA./SA._..._..._.{3,4}_.{0,3}_(none|local|travel|total)", 1),levels = c("none", "local", "travel", "total"), ordered = TRUE),
    beta = as.numeric(str_extract(sim, "SA./SA._(...)", group = 1)),
    gamma = as.numeric(str_extract(sim, "SA./SA._..._(...)", group = 1)),
    R0 = beta/gamma,
    sim_num = str_extract(sim, "(_.{1,3}).csv", 1))

```
# Population proportional SA mixing matrix
```{r}
sims %>% 
  filter(R0 == 1.4) %>% 
  ggplot() +
  aes(x = t, y = I) +
  geom_line(aes(col = mu, group = sim_num)) +
  facet_wrap(SA~Intervention, scales = "free")
```

```{r}
sim_stats <- sims %>% 
  group_by(sim_num, SA, Mixmat,mu,  Intervention, R0) %>% 
  summarise(peaksize = max(I),
            finalsize = max(S) - min(S),
            duration = max(t))
```
## peak size

```{r}
sim_stats %>% 
  filter() %>% 
  ggplot() + 
  aes(x = R0, y = peaksize) +
  geom_point(aes(col = mu)) +
  facet_grid(SA ~ Intervention)
```
## Final Size

```{r}
sim_stats %>% 
  filter(duration < 1000) %>% 
  ggplot() + 
  aes(x = R0, y = finalsize) +
  geom_point(aes(col = mu)
  )+
  facet_grid(SA ~ Intervention)
```

## Duration

### SA3
```{r}
sim_stats %>% 
  filter(duration < 1000, SA == "3") %>% 
  ggplot() + 
  geom_histogram(aes(x = duration, fill = mu))+
  facet_grid(Intervention ~ R0, scales = "free")

```
### SA4
```{r}
sim_stats %>% 
  filter(duration < 1000, SA == "4") %>% 
  ggplot() + 
  geom_histogram(aes(x = duration, fill = mu))+
  facet_grid(Intervention ~ R0, scales = "free")

```

