project:
  type: book
  output-dir: docs

book:
  title: "Hierarchical Spatial Structure in Compartmental Epidemiological models"
  author: "James Bender"
  description: "A thesis submitted for the degree of Graduate Diploma in Applied Statistics at The University of New England in 2023. School of Science and Technology."
  chapters:
    - index.qmd
    - abstract.qmd
    - declaration.qmd
    - acknowledgements.qmd
    - introduction.qmd
    - part: "Background"
      chapters:
       - Compartmental_Models.qmd
       - StochasticSIR.qmd
       - Metapopulation_Models.qmd
    - part: "Current Study"
      chapters:
       - Hierarchical_Models.qmd
       - Interventions.qmd
  appendices:
    - A-appA.qmd
  references: refs.qmd
  page-footer:
    left: "Created using <a href='https://quarto.org'>Quarto</a>. © 2023"
    border: false
    background: light
  sidebar:
    background: "#cccccc"
    style: "docked"

toc-title: "<b>Sections</b>"
html-math-method: katex
published-title: "Last updated"
date-format: "DD MMMM YYYY"
number-depth: 2
bibliography: thesisrefs.bib
csl: apa-single-spaced.csl
fig-height: 3.8
fig-width: 6.3
degreetype: Graduate Diploma of Applied Statistics
submitted: 2023
affiliation: School of Science and Technology
degrees: 'B.Sc. (Hons), University of Queensland'

execute:
  freeze: auto
  echo: false
  warning: false
  message: false

format:
  pdf:
    include-in-header:
      text: |
        \usepackage{algpseudocode}
        \usepackage{algorithm}
    include-before-body:
      text: |

        \algblock{Input}{EndInput}
        \algnotext{EndInput}
        \algblock{Output}{EndOutput}
        \algnotext{EndOutput}
        \newcommand{\Desc}[2]{\State \makebox[2em][l]{#1}#2}
        \renewcommand{\Return}{\State \textbf{return}~}
        \newcommand{\Print}{\State \textbf{print}~}
        \newcommand{\Break}{\State \textbf{break}}
        \newcommand{\Continue}{\State \textbf{continue}}
        \newcommand{\True}{\textbf{true}}
        \newcommand{\False}{\textbf{false}}
        \renewcommand{\And}{\textbf{and}~}
        \newcommand{\Or}{\textbf{or}~}
        \renewcommand{\Not}{\textbf{not}~}
        \newcommand{\To}{\textbf{to}~}
        \newcommand{\DownTo}{\textbf{downto}~}
    pdf-engine: xelatex
    toc-depth: 2


filters:
 - pseudocode
