# Abstract {.unnumbered}

Epidemiological modelling is essential to understand and predict the spread of infectious diseases and plan effective interventions. Disease spread is an inherently spatial process, particularly in diseases that spread through contact with body fluids, and spatially structured epidemiological models provide an opportunity to incorporate a wealth of geographical information into the modelling process. Here, we present a compartmental meta-population model encoding the hierarchical spatial structure of the Australian Statistical Geography Standard (ASGS). Relationships between spatial groupings are represented in a mixing matrix, which influences the spread of infection between patches (i.e. Patches in the same spatial grouping are more likely to spread disease to each other compared to patches outside this grouping). As an example, we model the Greater Melbourne Statistical Area (SA) with patches representing SA2, SA4, and SA4 level groupings, and stochastically simulate the course of an epidemic as a Continuous Time Markov Chain (CTMC). We compare the results of simulations with varying influence of the spatial relationships between patches (through the construction of the mixing matrix), different levels of spatial resolution (which level of the spatial hierarchy is represented by compartmental patches), and different infectious disease parameters (e.g. $R_0$), as well as with the results of a spatial compartmental model incorporating an alternative source of geographic information (i.e. empirically derived mobility data). We conclude by speculating on the potential use of such geographically informed epidemiological models in the management of infectious diseases.
