---
title: "DataRead"
editor: visual
---

```{r}
library(tidyverse)
```

# SA2 files
```{r}
SA2_files <- list.files("C:/Users/reubender/Downloads/SA2_julia", full.names = TRUE)

SA2_tot_files <- SA2_files[!str_detect(SA2_files, "patchinf|patchsus|summary")]

SA2_sims <- read_csv(SA2_tot_files, col_names = c("t", "S", "I"), skip = 2, id = "sim")

SA2_sims <- SA2_sims |>
  mutate(
    beta = as.numeric(str_extract(sim, "(...)_.{3}_.{3}_.{1,3}.csv", group = 1)),
    gamma = as.numeric(str_extract(sim, "(...)_.{3}_.{1,3}.csv", group = 1)),
    mm = as.numeric(str_extract(sim, "(...)_.{1,3}.csv", group = 1)),
    R0 = beta/gamma,
    SA = 2)


SA2_sims |> 
  filter(R0 <= 2, R0 > 1) |>
  ggplot() +
  aes(x = t, y = I, col = mm, group = sim) +
  geom_line() +
  facet_wrap(~R0, scales = "free")
```

# SA3


```{r}

SA3_files <- list.files("C:/Users/reubender/Downloads/SA3", full.names = TRUE)

SA3_tot_files <- SA3_files[!str_detect(SA3_files, "patchinf|patchsus|summary")]

SA3_sims <- read_csv(SA3_tot_files, col_names = c("t", "S", "I"), skip = 2, id = "sim")

SA3_sims <- SA3_sims |>
  mutate(
    beta = as.numeric(str_extract(sim, "(...)_.{3}_.{3}_.{1,3}.csv", group = 1)),
    gamma = as.numeric(str_extract(sim, "(...)_.{3}_.{1,3}.csv", group = 1)),
    mm = as.numeric(str_extract(sim, "(...)_.{1,3}.csv", group = 1)),
    R0 = beta/gamma,
    SA = 3)


SA3_sims |>
  ggplot() +
  aes(x = t, y = I, col = mm, group = sim) +
  geom_line() +
  facet_wrap(~R0, scales = "free")
```

# Moss
```{r}

Moss_files <- list.files("C:/Users/reubender/Downloads/Moss", full.names = TRUE)

Moss_tot_files <- Moss_files[!str_detect(Moss_files, "patchinf|patchsus|summary")]

Moss_sims <- read_csv(Moss_tot_files, col_names = c("t", "S", "I"), skip = 2, id = "sim")

Moss_sims <- Moss_sims |>
  mutate(
    beta = as.numeric(str_extract(sim, "(...)_.{3}_Moss_.{1,3}.csv", group = 1)),
    gamma = as.numeric(str_extract(sim, "(...)_Moss_.{1,3}.csv", group = 1)),
    R0 = beta/gamma,
    SA = 3, 
    mm = "Moss")


Moss_sims |>
  ggplot() +
  aes(x = t, y = I, col = mm, group = sim) +
  geom_line() +
  facet_wrap(~R0, scales = "free")
```

# All
```{r}
rbind(SA2_sims,
      SA3_sims
      ) |> 
  filter(R0 <= 2, R0 > 1) |>
  ggplot() +
  aes(x = t, y = I, col = mm, group = sim) +
  geom_line() +
  facet_grid(SA ~ R0, scales = "free")
```


```{r size}
rbind(SA2_sims,
      SA3_sims
      ) |> 
  filter(R0 >= 1) |> 
  group_by(sim, SA, R0, mm) |> 
  summarise(fin = min(S)) |> 
    ggplot() +
  aes(x = mm, y = fin, col = SA) +
  geom_point() +
  facet_grid(~ R0, scales = "free")
```

```{r duration}
rbind(SA2_sims,
      SA3_sims
      ) |> 
  filter(R0 <= 2, R0 > 1) |> 
  group_by(sim, SA, R0, mm) |> 
  summarise(duration = max(t)) |> 
    ggplot() +
  aes(x = mm, y = duration, col = factor(SA), alpha = 0.5) +
  geom_point() +
  facet_grid(~ R0, scales = "free")

rbind(SA2_sims,
      SA3_sims
      ) |> 
  filter(R0 <= 2, R0 > 1) |> 
  group_by(sim, SA, R0, mm) |> 
  summarise(duration = max(t)) |> 
    ggplot() +
  aes(x = factor(mm), y = duration, col = factor(SA), alpha = 0.5) +
  geom_boxplot() +
  facet_grid(~ R0, scales = "free")
```
```{r}
rbind(SA2_sims,
      SA3_sims
      ) |> 
  filter(R0 == 1.4) |> 
  group_by(sim, SA, R0, mm) |> 
  summarise(fin = min(S)) |> 
    ggplot() +
  aes(x = fin, col = SA, group = sim) +
  geom_histogram(bins = 100) +
  facet_grid(mm ~ SA)
```
