# SIS DTMC

The compartmental model
```{mermaid}
flowchart LR
    S --> I
    I --> S
```
Can be described by a Markov chain of a random variable I(t) representing the number of individuals infected at time t.


```{dot}
digraph {
    rankdir = "LR"
    0 -> 0
    1 -> 0
    1 -> 2
    2 -> 1
    2 -> "..."
    "..." -> 2
    "..." -> N
    N -> "..."
}   
```
Note that I(t) = 0 is an absorbing state (i.e. if there are no infectious people they cannot infect anyone). All other states {1,..., N} are transient. 

Possible transitions are specified by

$$
p _ {ji} ( \Delta t ) =
     \begin{cases}
        {\frac { \beta i ( N - i ) } { N}} \Delta t, & {j = i + 1 } \\ 
        { \gamma i \Delta t}, & { j = i - 1 } \\ 
        { 1 - \bigg[ \frac { \beta i (N - i) } { N } +  \gamma i }\bigg] \Delta t, & { j = i } \\
        0, & { j \neq i +1, i, i-1}
    \end{cases}
$$ {#eq-SIS_DTMC_Trans} 

Which can be simplified to

$$
p _ {ji} ( \Delta t ) =
    \begin{cases}
        b(i) \Delta t, & {j = i + 1 } \\ 
        d(i) \Delta t, & { j = i - 1 } \\ 
        1 - [ b(i)  + d(i)] \Delta t, & { j = i } \\
        0, & { j \neq i +1, i, i-1}
    \end{cases}
$$ {#eq-SIS_DTMC_Trans_BD}

The probability of being in state $i$ at time $t + \Delta t$ can be experessed in terms of probabilities at time $t$.
$$
p_{i}(t + \Delta t) =
    p_{i-1}(t)b(i-1)\Delta t +
    p_{i+1}(t)d(i+1)\Delta t +
    p_{i}(t)(1- [ b(i)  + d(i)] \Delta t)
$$ 

for $i = 1,2,..., N$, where $b(i) = \beta (N-1/N)$, and $d(i)= \gamma i$

The transition matrix $P(\Delta t)$ is given by
$$
\begin{pmatrix}
    1 & d(1)\Delta t & 0 &  \cdots & 0 & 0 \\
    0  & 1-(b+d)(1)\Delta t & d(2)\Delta t &  \cdots & 0 & 0 \\
    0 & b(1)\Delta t & 1-(b+d)(1)\Delta t &  \cdots & 0 & 0 \\
    0 & 0t & b(1)\Delta &  \cdots & 0 & 0 \\
    \vdots & \vdots & \vdots &  \ddots & \vdots & \vdots \\
    0 & 0  & 0 &  \cdots & d(N-1) \Delta t & 0 \\
    0 & 0  & 0 &  \cdots & 1-(b+d)(N-1)\Delta t & d(N) \Delta t \\
    0 & 0  & 0 &  \cdots & b(N-1)\Delta t & 1- d(N) \Delta t \\
\end{pmatrix}
$$


# SIR DTMC

The compartmental model
```{mermaid}
flowchart LR
    S --> I
    I --> R
```
Can be described by a Markov chain of random variables S(t) and I(t) representing the number of susceptible or individuals infected at time t, respectively.


```{dot}
digraph {
    rankdir = "LR"
    "S = 0 \n I = 1" ->    "S = 0 \n I = 0" 

    "S = 0 \n I = 2" ->    "S = 0 \n I = 1" 

    "S = 0 \n I = ~" ->    "S = 0 \n I = 2"

    "S = 0 \n I = N" ->    "S = 0 \n I = ~"


    "S = 1 \n I = 1" ->    "S = 0 \n I = 2" 

    "S = 1 \n I = 2" ->    "S = 1 \n I = 1"
    "S = 1 \n I = 2" ->    "S = 0 \n I = ~"

    "S = 1 \n I = ~" ->    "S = 1 \n I = 2"
    "S = 1 \n I = ~" ->    "S = 0 \n I = ~"
    "S = 1 \n I = ~" ->    "S = 0 \n I = N - 1"

    "S = 1 \n I = N - 1" -> "S = 1 \n I = N - 2"
    "S = 1 \n I = N - 1" -> "S = 0 \n I = N"

    "S = 1 \n I = N - 2" -> "S = 0 \n I = N -  1"
    "S = 1 \n I = N - 2" -> "S = 1 \n I = ~"


    "S = 2 \n I = 1" ->    "S = 1 \n I = 2"
    "S = 2 \n I = 1" ->    "S = 2 \n I = 0"

    "S = 2 \n I = 2" ->    "S = 1 \n I = ~"
    "S = 2 \n I = 2" ->    "S = 2 \n I = 1"

    "S = 2 \n I = ~" ->    "S = 1 \n I = ~"
    "S = 2 \n I = ~" ->    "S = 1 \n I = N - 2"
    "S = 2 \n I = ~" ->    "S = 2 \n I = 2"
    
    "S = 2 \n I = N - 2" -> "S = 1 \n I = N - 1"
    "S = 2 \n I = N - 2" -> "S = 2 \n I = ~"
    

    "S = ~ \n I = 1" ->    "S = ~ \n I = 0"
    "S = ~ \n I = 1" ->    "S = ~ \n I = 2"
    "S = ~ \n I = 1" ->    "S = 2 \n I = 2"

    "S = ~ \n I = 2" ->    "S = ~ \n I = ~"
    "S = ~ \n I = 2" ->    "S = 2 \n I = ~"
    "S = ~ \n I = 2" ->    "S = ~ \n I = 1"

    "S = ~ \n I = ~" ->    "S = 2 \n I = ~"
    "S = ~ \n I = ~" ->    "S = 2 \n I = N-2"
    "S = ~ \n I = ~" ->    "S = ~ \n I = ~"
    "S = ~ \n I = ~" ->    "S = ~ \n I = N-2"

    "S = ~ \n I = ~" ->    "S = ~ \n I = ~"
    "S = ~ \n I = ~" ->    "S = ~ \n I = 2"

    "S = N - 1 \n I = 1" ->    "S = N - 2 \n I = 2"
    "S = N - 1 \n I = 1" ->    "S = N - 1\n I = 0"

    "S = N - 2 \n I = 1" -> "S = ~ \n I = 2"
    "S = N - 2 \n I = 1" -> "S = N - 2 \n I = 0"

    "S = N - 2 \n I = 2" -> "S = ~ \n I = ~"
    "S = N - 2 \n I = 2" -> "S = N - 2 \n I = 1"
}   
```
Note that I(t) = 0 is an absorbing state (i.e. if there are no infectious people they cannot infect anyone). All other states {1,..., N} are transient. 

Possible transitions are specified by

$$
p _ {ji} ( \Delta t ) =
     \begin{cases}
        {\frac { \beta i ( N - i ) } { N}} \Delta t, & {j = i + 1 } \\ 
        { \gamma i \Delta t}, & { j = i - 1 } \\ 
        { 1 - \bigg[ \frac { \beta i (N - i) } { N } +  \gamma i }\bigg] \Delta t, & { j = i } \\
        0, & { j \neq i +1, i, i-1}
    \end{cases}
$$ {#eq-SIS_DTMC_Trans} 

Which can be simplified to

$$
p _ {ji} ( \Delta t ) =
    \begin{cases}
        b(i) \Delta t, & {j = i + 1 } \\ 
        d(i) \Delta t, & { j = i - 1 } \\ 
        1 - [ b(i)  + d(i)] \Delta t, & { j = i } \\
        0, & { j \neq i +1, i, i-1}
    \end{cases}
$$ {#eq-SIS_DTMC_Trans_BD}

The probability of being in state $i$ at time $t + \Delta t$ can be experessed in terms of probabilities at time $t$.
$$
p_{i}(t + \Delta t) =
    p_{i-1}(t)b(i-1)\Delta t +
    p_{i+1}(t)d(i+1)\Delta t +
    p_{i}(t)(1- [ b(i)  + d(i)] \Delta t)
$$ 

for $i = 1,2,..., N$, where $b(i) = \beta (N-1/N)$, and $d(i)= \gamma i$

The transition matrix $P(\Delta t)$ is given by
$$
\begin{pmatrix}
    1 & d(1)\Delta t & 0 &  \cdots & 0 & 0 \\
    0  & 1-(b+d)(1)\Delta t & d(2)\Delta t &  \cdots & 0 & 0 \\
    0 & b(1)\Delta t & 1-(b+d)(1)\Delta t &  \cdots & 0 & 0 \\
    0 & 0t & b(1)\Delta &  \cdots & 0 & 0 \\
    \vdots & \vdots & \vdots &  \ddots & \vdots & \vdots \\
    0 & 0  & 0 &  \cdots & d(N-1) \Delta t & 0 \\
    0 & 0  & 0 &  \cdots & 1-(b+d)(N-1)\Delta t & d(N) \Delta t \\
    0 & 0  & 0 &  \cdots & b(N-1)\Delta t & 1- d(N) \Delta t \\
\end{pmatrix}
$$
