name: Quarto Publish
on:
  push:
    branches: 
      - main

jobs:
    build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
  
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2

        - name: Render
          uses: quarto-dev/quarto-actions/render@v2
          with:
            to: html
            path: papers/Manuscript
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Publish to GitHub Pages (and render)
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages
            path: papers/Manuscript
