name: Quarto Publish
on:
  push:
    branches: 
      - main

jobs:
    build-deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
  
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          
        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            packages:
              any::knitr
              any::rmarkdown
              any::downlit
              any::xml2
            
        - name: Render
          uses: quarto-dev/quarto-actions/render@v2
          with:
            to: pdf
            path: papers/Manuscript
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}