---
title: "R0 in metapopulations"
editor: 
  markdown: 
    wrap: 72
---

In a simple SIR model, the basic reproduction number, i.e. the expected
number of infections caused by a single infectious individual in a
population composed otherwise of susceptibles,
$R_0 = \frac{\beta}{\gamma}$. However, in hetrogenous populations, such
as in the metapopulations under consideration in this thesis, this
simple formula may not hold. It has been shown that $R_0$ can be more
generally characterised by as the dominant eigenvalue of the 'next
generation matrix' $K$, which relates the numbers of newly infected
individuals in the various patches though consecutive 'generations' of
infection (@Diekmmann1990).

We follow @Diekman2010, and @Feng2015 in characterising the NGM for the
subclass of metapopulation models considered in this thesis to prove
that in most of these cases the relationship
$R_0 = \frac{\beta}{\gamma}$ indeed holds.

First, consider the 'infectious subsytem' of the model presented in
@eq-SIR_metapop_ODE, i.e. $$
\frac{dI_i}{dt} =\Lambda_i \cdot \frac{S_i}{N_{i}}-\gamma I_i = \sum\limits_j^n\beta \frac{S_i I_j m_{i,j}}{N_{i}}-\gamma I_i
$$

The Jacobian of this system

$$J=
\left(
\begin{array}{ccc}
\frac{\partial I'_{1}}{\partial I_{1}} & \cdots & \frac{\partial I'_{1}}{\partial I_{n}}\\
\vdots  &  \ddots  & \vdots \\
\frac{\partial I'_{n}}{\partial I_{1}} & \cdots & \frac{\partial f_{2}}{\partial I_{2}}
\end{array}
\right) =
\left(
\begin{array}{ccc}
m_{11} \beta-\gamma & \cdots & m_{1n} \beta \\
\vdots & \ddots & \vdots\\
m_{n1} \beta & \cdots & m_{nn} \beta-\gamma
\end{array}
\right)$$

can be decomposed in to contributions of the Transmission matrix $T$ and
the Transition matrix $\Sigma$ $$
J = T\Sigma
$$ such that $$
T = \left(\begin{array}{ccc}
m_{11} \beta & \cdots & m_{1n} \beta \\
\vdots & \ddots & \vdots\\
m_{n1} \beta & \cdots & m_{nn} \beta
\end{array}\right)
$$

where $T_ij$ is the rate at which an individual in infected state $j$
produces individuals with infected state $i$, and $$
\Sigma = \left(\begin{array}{ccc}
\gamma & \cdots & 0 \\
\vdots & \ddots & \vdots\\
0 & \cdots & \gamma
\end{array}\right)
$$ where $\Sigma_{ij}$ can be interpreted as the expected time that an
individual who presently has infected state $j$ will spend in infected
state $i$ @Diekman2010

The Next generation Matrix

$$
\begin{aligned}
K = & -T\Sigma^{-1}\\
K = & \left(\begin{array}{ccc}
m_{11} \beta & \cdots & m_{1n} \beta \\
\vdots & \ddots & \vdots\\
m_{n1} \beta & \cdots & m_{nn} \beta
\end{array}\right) \times \left(\begin{array}{ccc}
\gamma & \cdots & 0 \\
\vdots & \ddots & \vdots\\
0 & \cdots & \gamma
\end{array}\right)^{-1}\\
K= & \left(\begin{array}{ccc}
m_{11} \frac{\beta}{\gamma} & \cdots & m_{1n} \frac{\beta}{\gamma} \\
\vdots & \ddots & \vdots\\
m_{n1} \frac{\beta}{\gamma} & \cdots & m_{nn} \frac{\beta}{\gamma}
\end{array}\right)
\end{aligned}
$$

where $K_{ij}$ is the expected number of new infections in patch $i$
generated by one newly infected infividual in patch $j$. In our case
where $\beta$ and $\gamma$ are constant scalar values (i.e. homogenous
across patches), this reduces to $$
K = \frac{\beta}{\gamma} M
$$ Where $M$ is our mixing matrix. Furthermore, the constraint that M be
a stochastic matrix, ie.

$$
\begin{aligned}
0 \leq m_{ij} \leq 1 \\
\sum\limits_j m_{ij} = 1; 
\end{aligned}
$$

entails (via 'Gershgorin circle theorem') that $M$ has a dominant
eigenvalue of 1. i.e. there is a vector
